# Step 2
# Creates reference sheets for the other 7 counterbalanced stimulus lists
# Reference sheet generated by script1 used as starting point

import pandas as pd
import os

newPath = "reference/"
if not os.path.exists(newPath):
    os.makedirs(newPath)

os.rename("list1_reference.csv", "reference/list1_reference.csv")
os.chdir("reference/")

# Read in reference sheet created from first file
list1 = pd.read_csv("list1_reference.csv", sep=",")

# List 2: items assigned to new 1 vs. 2 block (same trial length as in list 1)
# Trial previously in repeated in block 1 and non-repeated in block 2
# now non-repeated in block 1 and repeated in block 2, etc.
# Assignment of filler trials to blocks decided in script to create lists
list2 = pd.DataFrame.copy(list1)
list2['block'] = list2['block'].map({'1A': '2A', '2A': '1A', '1B': '2B', '2B': '1B', "any": "any"})
saveFile = open('list2_reference.csv', 'w')
pd.DataFrame.to_csv(list2, saveFile, index=False)
saveFile.close()

# List 3: items assigned new trial length (same blocks as list 1)
# Trial previously length 3, now length 4
# Length of filler trials are decided randomly in script to create lists
list3 = pd.DataFrame.copy(list1)
list3['length'] = list3['length'].map({'3': '4', '4': '3', "any": "any"})
saveFile = open('list3_reference.csv', 'w')
pd.DataFrame.to_csv(list3, saveFile, index=False)
saveFile.close()

# List 4: items assigned to new 1 vs. 2 block (same trial length as list 3)
list4 = pd.DataFrame.copy(list3)
list4['block'] = list4['block'].map({'1A': '2A', '2A': '1A', '1B': '2B', '2B': '1B', "any": "any"})
saveFile = open('list4_reference.csv', 'w')
pd.DataFrame.to_csv(list4, saveFile, index=False)
saveFile.close()

# List 5: items assigned to new A vs. B block (same trial length as list 1)
# Trials previously in A blocks now in B blocks, and vice versa
list5 = pd.DataFrame.copy(list1)
list5['block'] = list5['block'].map({'1A': '1B', '2A': '2B', '1B': '2A', '2B': '1A', "any": "any"})
saveFile = open('list5_reference.csv', 'w')
pd.DataFrame.to_csv(list5, saveFile, index=False)
saveFile.close()

# List 6: items assigned to new 1 vs. 2 block (same A vs. B assignment as list 5)
list6 = pd.DataFrame.copy(list5)
list6['block'] = list6['block'].map({'1A': '2A', '2A': '1A', '1B': '2B', '2B': '1B', "any": "any"})
saveFile = open('list6_reference.csv', 'w')
pd.DataFrame.to_csv(list6, saveFile, index=False)
saveFile.close()

# List 7: items assigned new trial length (same blocks as list 6)
list7 = pd.DataFrame.copy(list6)
list7['length'] = list7['length'].map({'3': '4', '4': '3', "any": "any"})
saveFile = open('list7_reference.csv', 'w')
pd.DataFrame.to_csv(list7, saveFile, index=False)
saveFile.close()

# List 8: items assigned to new 1 vs. 2 block (same trial length as list 7)
list8 = pd.DataFrame.copy(list7)
list8['block'] = list8['block'].map({'1A': '2A', '2A': '1A', '1B': '2B', '2B': '1B', "any": "any"})
saveFile = open('list8_reference.csv', 'w')
pd.DataFrame.to_csv(list8, saveFile, index=False)
saveFile.close()